language: generic
script: "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: ea50756eca0f
  - secure: j7jVn+Y+lMbXY1mEAyXrC8jQKioYP8FDaIl4rR7iISVwG7Bn4xmp9237Jl324TdrXM8B0qJqV/VvPzIAui3r4Kj78oRAqNb5gJBBxJVp0LasbhCOFAd//bG0jeISzxe6tSUTq0Yxt7UIpBgEtpYuJwrP4RhjUy6NuvnxLxZ4VxqjTfFdusYz6jPu9p0t4CBo3HlF45FFV5KsLbeh5BuvgjWK+t0t8zWUSOFDhfIbDVpX7KNs/JS0PO0FQ7U9tmvuPvEI5EpYt43zkbQF058TfqHhYMYqBN9UAc2qZDaxY9rkdKAHjnHZ5U1/vKI7kxZhsfQ6H09HFkKQYxa3kmI2Rgs5f/QX5qKYc6nxk6Dr+9SFaWthWp6G+5Zi0Lczu6H7quJ6yNPyZpBm00XG/o+yIZFdEYiz8eTqV9ChnPmfWBR73p8ZoWQSYAx0Eb02cUnaI+luXUcKnP5cZxjMnpOsjdJMV/iNog8IDnUAr/lUJqfBiitufstB9jzs6+aLsN1L+eylOzGtonUxAOI/BzbMD5Va5JyeBFkmfhBm5LtwHvcEC7XPDOcZ7my+Q8jT9Sdaiwxd3Bf1ujWL3Femzcnd3bdubTdLaENfHuyzQ6nVW7ewvyT3IAwMySNX7AXXq1wjRTsvqTeQ2y9K/Kh2RxwnnZZ+LcilrP2gGNSlzRAHVEU=
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: U1d+r8okigRkYYqVBs+lDqSFyuBTkvb1q7RD67JuupJdqSfW1tLFA62ruRwJJ2SJyhUPozs4CTUow/AvhJ2/WEtkYVDTxyRU4TF+QZm2Xtv2lSowyHBmyCCmBTqzj49g2mWpWcH9CW2zeIXQg/dq41bkmcSZRixYQijgTAuAkCATnIcWJ0mN3WqKSugrGI0AureJWtDfosCfFRBOqcp4WeXwwvn0v4JuMNX132tDd8Zel/9mHsbDbW93unlfdQ4nlXB4TgjOoFVo+WBLOBUfgbBaMXgmglAB0w1/ccCZnC2CjfXXMbNwoS3VtRNG9tb1cMoQqPlcjaRbZFDMV2BZlpqfWY3L8QJDFmVaTIiU0aBb1tWjXrOuyGgRlpN/hYXwePlTR+eNXzdQJHChRU+l2apC6xnQWrjjyiMkEX974ej45onuvVfdntPHBD4/UUY3luhJaO+MYj/xc/z3SbNdMMp/dcogWH9dtqsiTUwSHI9FY6IqXE4/1nwohWNON3eSDwlVHz4yCWeLtnvIphS229+3BlyYEOzgGrHasEO97xG2GiAavGL8bPeLKBlMnmo+0EsRfO2OfkQjp9BCreBfHloV/TjXTv9d/trOBnt+337RnNqWleK7oX9tG6XIEmOQzdKA/3PMo/xvUWV6K3eTNTBRSU0HWcfwhdNsXsXJ9s4=
  file: kps
  skip_cleanup: true
  on:
    condition: "$TRAVIS_TEST_RESULT == 0"
